//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioClientePublico.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidoP {
            get {
                return this.apellidoPField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPField, value) != true)) {
                    this.apellidoPField = value;
                    this.RaisePropertyChanged("apellidoP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidoM {
            get {
                return this.apellidoMField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMField, value) != true)) {
                    this.apellidoMField = value;
                    this.RaisePropertyChanged("apellidoM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceEjemploSoap")]
    public interface WebServiceEjemploSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroAleatorio", ReplyAction="*")]
        int numeroAleatorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroAleatorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> numeroAleatorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        int suma(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> sumaAsync(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertirFtoC", ReplyAction="*")]
        double convertirFtoC(double temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertirFtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> convertirFtoCAsync(double temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertirCtoF", ReplyAction="*")]
        double convertirCtoF(double temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertirCtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<double> convertirCtoFAsync(double temperatura);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sid del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        ServicioClientePublico.ServiceReference2.getDataResponse getData(ServicioClientePublico.ServiceReference2.getDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataResponse> getDataAsync(ServicioClientePublico.ServiceReference2.getDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getDataAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataAll", ReplyAction="*")]
        ServicioClientePublico.ServiceReference2.getDataAllResponse getDataAll(ServicioClientePublico.ServiceReference2.getDataAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataAllResponse> getDataAllAsync(ServicioClientePublico.ServiceReference2.getDataAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getData", Namespace="http://tempuri.org/", Order=0)]
        public ServicioClientePublico.ServiceReference2.getDataRequestBody Body;
        
        public getDataRequest() {
        }
        
        public getDataRequest(ServicioClientePublico.ServiceReference2.getDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sid;
        
        public getDataRequestBody() {
        }
        
        public getDataRequestBody(string sid) {
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioClientePublico.ServiceReference2.getDataResponseBody Body;
        
        public getDataResponse() {
        }
        
        public getDataResponse(ServicioClientePublico.ServiceReference2.getDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioClientePublico.ServiceReference2.Usuario getDataResult;
        
        public getDataResponseBody() {
        }
        
        public getDataResponseBody(ServicioClientePublico.ServiceReference2.Usuario getDataResult) {
            this.getDataResult = getDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataAll", Namespace="http://tempuri.org/", Order=0)]
        public ServicioClientePublico.ServiceReference2.getDataAllRequestBody Body;
        
        public getDataAllRequest() {
        }
        
        public getDataAllRequest(ServicioClientePublico.ServiceReference2.getDataAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDataAllRequestBody {
        
        public getDataAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioClientePublico.ServiceReference2.getDataAllResponseBody Body;
        
        public getDataAllResponse() {
        }
        
        public getDataAllResponse(ServicioClientePublico.ServiceReference2.getDataAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioClientePublico.ServiceReference2.Usuario[] getDataAllResult;
        
        public getDataAllResponseBody() {
        }
        
        public getDataAllResponseBody(ServicioClientePublico.ServiceReference2.Usuario[] getDataAllResult) {
            this.getDataAllResult = getDataAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEjemploSoapChannel : ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEjemploSoapClient : System.ServiceModel.ClientBase<ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap>, ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap {
        
        public WebServiceEjemploSoapClient() {
        }
        
        public WebServiceEjemploSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEjemploSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjemploSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjemploSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int numeroAleatorio() {
            return base.Channel.numeroAleatorio();
        }
        
        public System.Threading.Tasks.Task<int> numeroAleatorioAsync() {
            return base.Channel.numeroAleatorioAsync();
        }
        
        public int suma(int val1, int val2) {
            return base.Channel.suma(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> sumaAsync(int val1, int val2) {
            return base.Channel.sumaAsync(val1, val2);
        }
        
        public double convertirFtoC(double temperatura) {
            return base.Channel.convertirFtoC(temperatura);
        }
        
        public System.Threading.Tasks.Task<double> convertirFtoCAsync(double temperatura) {
            return base.Channel.convertirFtoCAsync(temperatura);
        }
        
        public double convertirCtoF(double temperatura) {
            return base.Channel.convertirCtoF(temperatura);
        }
        
        public System.Threading.Tasks.Task<double> convertirCtoFAsync(double temperatura) {
            return base.Channel.convertirCtoFAsync(temperatura);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioClientePublico.ServiceReference2.getDataResponse ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap.getData(ServicioClientePublico.ServiceReference2.getDataRequest request) {
            return base.Channel.getData(request);
        }
        
        public ServicioClientePublico.ServiceReference2.Usuario getData(string sid) {
            ServicioClientePublico.ServiceReference2.getDataRequest inValue = new ServicioClientePublico.ServiceReference2.getDataRequest();
            inValue.Body = new ServicioClientePublico.ServiceReference2.getDataRequestBody();
            inValue.Body.sid = sid;
            ServicioClientePublico.ServiceReference2.getDataResponse retVal = ((ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap)(this)).getData(inValue);
            return retVal.Body.getDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataResponse> ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap.getDataAsync(ServicioClientePublico.ServiceReference2.getDataRequest request) {
            return base.Channel.getDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataResponse> getDataAsync(string sid) {
            ServicioClientePublico.ServiceReference2.getDataRequest inValue = new ServicioClientePublico.ServiceReference2.getDataRequest();
            inValue.Body = new ServicioClientePublico.ServiceReference2.getDataRequestBody();
            inValue.Body.sid = sid;
            return ((ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap)(this)).getDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioClientePublico.ServiceReference2.getDataAllResponse ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap.getDataAll(ServicioClientePublico.ServiceReference2.getDataAllRequest request) {
            return base.Channel.getDataAll(request);
        }
        
        public ServicioClientePublico.ServiceReference2.Usuario[] getDataAll() {
            ServicioClientePublico.ServiceReference2.getDataAllRequest inValue = new ServicioClientePublico.ServiceReference2.getDataAllRequest();
            inValue.Body = new ServicioClientePublico.ServiceReference2.getDataAllRequestBody();
            ServicioClientePublico.ServiceReference2.getDataAllResponse retVal = ((ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap)(this)).getDataAll(inValue);
            return retVal.Body.getDataAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataAllResponse> ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap.getDataAllAsync(ServicioClientePublico.ServiceReference2.getDataAllRequest request) {
            return base.Channel.getDataAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioClientePublico.ServiceReference2.getDataAllResponse> getDataAllAsync() {
            ServicioClientePublico.ServiceReference2.getDataAllRequest inValue = new ServicioClientePublico.ServiceReference2.getDataAllRequest();
            inValue.Body = new ServicioClientePublico.ServiceReference2.getDataAllRequestBody();
            return ((ServicioClientePublico.ServiceReference2.WebServiceEjemploSoap)(this)).getDataAllAsync(inValue);
        }
    }
}
